reloj_checador_team03/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :branches
  resources :employees
  resources :attendances
  get 'users/index'
  get 'reports/attendance_by_day'
  post 'reports/attendance_by_day'
  get 'reports/average_time_employees'
  get 'reports/absence_employee'
  post 'reports/absence_employee'
  post 'employees/search', :to => 'employees#search'
  post 'users/search', :to => 'users#search'
  post 'branches/search', :to => 'branches#search'
  root 'attendances#new'

  
end

reloj_checador_team03/app/models/branch.rb
class Branch < ApplicationRecord

  validates :name, presence: true
  validates :address, presence: true

    def self.search(text)
        if text.blank?  # blank? covers both nil and empty string
          all
        else
          where('name LIKE ? or address LIKE ?', "%#{text}%", "%#{text}%")
        end
    end
end

reloj_checador_team03/app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: %i[ show edit update destroy ]

  # GET /branches or /branches.json
  def index
    @branches = Branch.all.page(params[:page])
  end

  def search 
    @branches = Branch.search(params[:search]).page(params[:page])
  end

  # GET /branches/1 or /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches or /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branches_url, notice: "Branch was successfully created." }
        format.json { render :index, status: :created, location: @branch }
      else
        format.js { render :new } 
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1 or /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to branches_url, notice: "Branch was successfully updated." }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.js { render :edit } 
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1 or /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: "Branch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def branch_params
      params.require(:branch).permit(:name, :address)
    end
end

reloj_checador_team03/app/helpers/branches_helper.rb
module BranchesHelper
end

reloj_checador_team03/app/views/branches/_form.html.erb
<div class="modal-dialog">
<% @branch= Branch.new if @branch.nil?  %>
<%  if request.path.include?('edit') then text = 'Edit Branch' else text = 'Create a new Branch' end %>
<%= simple_form_for(@branch , remote: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= text %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= f.submit "Save branch", :class => 'btn btn-primary create-button' %>
      </div>
    </div>
    <% end %>
  </div>

reloj_checador_team03/app/views/branches/_search.erb
<% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.address %></td>
        <td><i class="far fa-edit"></i><%= link_to 'Edit', edit_branch_path(branch), remote: true %> &nbsp <i class="fas fa-user-times"></i><%= link_to 'Delete', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

reloj_checador_team03/app/views/branches/edit.html.erb
<h1>Edit Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

reloj_checador_team03/app/views/branches/edit.js.erb
$("#branch-modal").html("<%= j render 'form' %>");
$('#branch-modal').modal('show');

reloj_checador_team03/app/views/branches/index.html.erb
<%= toastr_flash %>
<h1>Branches</h1>
<div class="container-content">

  <div class="d-flex justify-content-between bd-highlightm mb-3">
    <div class="d-flex justify-content-start">
     <%= form_tag(branches_search_path, method: "post", remote: true, authenticity_token: true, role: "form",class: "form") do %>
     <%= text_field_tag('search', nil, placeholder: 'Enter search term...', class: 'form-control') %>
     <% end %>
    </div>

    <div class="d-flex justify-content-center">
      <%= link_to 'New Branch', new_branch_path(Branch.new), remote: true, :class => "btn btn-success create-button" %>
    </div>
  </div>

  <div class="modal fade" id="branch-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <%= render "form"  %>
  </div>


  <table class="table">
    <thead class="table-thead">
      <tr>
        <th class="table-thead-th">Name</th>
        <th class="table-thead-th">Address</th>
        <th class="table-thead-th">Actions</th>
      </tr>
    </thead>

    <tbody id="branch-table-body">
      <%= render 'search', remote: true %>
    </tbody>
  </table>
    <%= paginate @branches %>
</div>

reloj_checador_team03/app/views/branches/new.html.erb
<h1>New Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Back', branches_path %>

reloj_checador_team03/app/views/branches/new.js.erb
$("#branch-modal").html("<%= j render 'form' %>");
$('#branch-modal').modal('show');

reloj_checador_team03/app/views/branches/search.js.erb
$('#branch-table-body').html("<%= j (render 'search', branches: @branches) %>")

reloj_checador_team03/app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @branch.address %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>