reloj_checador_team03/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :branches
  resources :employees
  resources :attendances
  get 'users/index'
  get 'reports/attendance_by_day'
  post 'reports/attendance_by_day'
  get 'reports/average_time_employees'
  get 'reports/absence_employee'
  post 'reports/absence_employee'
  post 'employees/search', :to => 'employees#search'
  post 'users/search', :to => 'users#search'
  post 'branches/search', :to => 'branches#search'
  root 'attendances#new'

  
end

reloj_checador_team03/app/controllers/reports_controller.rb
class ReportsController < ApplicationController

    def attendance_by_day
        @attendances = Attendance.attendance_by_day(params[:first_date])
    end

    def average_time_employees
    end

    def absence_employee
        @absences = Attendance.absence_employee(params[:first_date])
        @attendances = Attendance.attendance_by_day(params[:first_date])
    end
end

reloj_checador_team03/app/helpers/reports_helper.rb
module ReportsHelper
end

reloj_checador_team03/app/views/reports/_search.html.erb
<% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.date_time.strftime("%m/%d/%Y %I:%M") %></td>
        <td><%= attendance.employee.fullname %></td>
        <td><%= attendance.type_check %></td>
      </tr>
<% end %>

reloj_checador_team03/app/views/reports/_search_absence.html.erb
<% unless @absences.nil? %>
  <% @absences.each do |absence| %>
      <tr>
        <td><%= absence["name"] %> <%= absence["last_name"] %></td>
        <td><%= absence["absence"] %></td>
      </tr>
  <% end %>
<% end %>

reloj_checador_team03/app/views/reports/absence_employee.html.erb
<h1>Report Absence Per Employee per month</h1>

<div class="container-content">
<div class="d-flex justify-content-between bd-highlight mb-6">
  <div class="d-flex justify-content-start ">
     <%= form_tag(reports_absence_employee_path, method: "post", remote: true, authenticity_token: true, role: "form",class: "form-row") do %>
      <%= text_field_tag 'first_date', "Select Date One", class: 'flatpickr datepicker form-control' %>    
      <%= submit_tag "Search", :class => 'btn btn-primary create-button' %>
     <% end %>
  </div>
  
</div>
<table class="table">
  <thead>
    <tr>
      <th>Employee</th>
      <th>Absences</th>
    </tr>
  </thead>

    <tbody id="absence_by_month">
    <%= render 'search_absence', remote: true %>
  </tbody>
</table>

</div>

<script>
flatpickr(".datepicker", {})
</script>

reloj_checador_team03/app/views/reports/absence_employee.js.erb
$('#absence_by_month').html("<%= j (render 'search_absence', absences: @absences) %>");

reloj_checador_team03/app/views/reports/absence_per_month.html.erb
<%= toastr_flash %>
<h1>Absence report by month</h1>
<div class="container-content">


</div>

reloj_checador_team03/app/views/reports/attendance_by_day.html.erb
<h1>Report Attendance By Day</h1>

<div class="container-content">
<div class="d-flex justify-content-between bd-highlight mb-6">
  <div class="d-flex justify-content-start ">
     <%= form_tag(reports_attendance_by_day_path, method: "post", remote: true, authenticity_token: true, role: "form",class: "form-row") do %>
      <%= text_field_tag 'first_date', "Select Date One", class: 'flatpickr datepicker form-control' %>    
      <%= submit_tag "Search", :class => 'btn btn-primary create-button' %>
     <% end %>
  </div>
  
</div>
<table class="table">
  <thead>
    <tr>
      <th>Date attendance</th>
      <th>Employee</th>
      <th>Detail</th>
    </tr>
  </thead>

    <tbody id="attendance_by_day">
    <%= render 'search', remote: true %>
  </tbody>
</table>

</div>

<script>
flatpickr(".datepicker", {})
</script>

reloj_checador_team03/app/views/reports/attendance_by_day.js.erb
$('#attendance_by_day').html("<%= j (render 'search', attendances: @attendances) %>")

reloj_checador_team03/app/views/reports/average_time.html.erb
<%= toastr_flash %>
<h1>Average time employees checked in/out by month</h1>
<div class="container-content">


</div>

reloj_checador_team03/app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

reloj_checador_team03/app/views/reports/stats_per_day.html.erb
<%= toastr_flash %>
<h1>Attendance by day</h1>
<div class="container-content">


</div>