reloj_checador_team03/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :branches
  resources :employees
  resources :attendances
  get 'users/index'
  get 'reports/attendance_by_day'
  post 'reports/attendance_by_day'
  get 'reports/average_time_employees'
  get 'reports/absence_employee'
  post 'reports/absence_employee'
  post 'employees/search', :to => 'employees#search'
  post 'users/search', :to => 'users#search'
  post 'branches/search', :to => 'branches#search'
  root 'attendances#new'

  
end

reloj_checador_team03/app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true
  validates :last_name, presence: true
  validates :position, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :private_number, numericality: { only_integer: true }

    def self.search(text)
        if text.blank?  # blank? covers both nil and empty string
          all
        else
          where('name LIKE ? or last_name LIKE ? or email LIKE ?', "%#{text}%", "%#{text}%", "%#{text}%")
        end
    end

    def fullname
      "#{self.name} #{self.last_name}"
    end
end

reloj_checador_team03/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all.page(params[:page])
  end

  def search
   @employees = Employee.search(params[:search]).page(params[:page])
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_url, notice: "Employee was successfully created." }
        format.json { render :index, status: :created, location: @employee }
      else
        format.js { render :new } 
        format.html { render :new }
        format.json { render json: @clock_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_url, notice: "Employee was successfully updated." }
        format.json { render :index, status: :ok, location: @employee }
      else
        format.js { render :edit } 
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :last_name, :position, :email, :private_number, :search)
    end
end

reloj_checador_team03/app/helpers/employees_helper.rb
module EmployeesHelper
end

reloj_checador_team03/app/views/employees/_form.html.erb
<div class="modal-dialog">
<% @employee= Employee.new if @employee.nil? %>
<%  if request.path.include?('edit') then text = 'Edit Employee' else text = 'Create a new Employee' end %>
<%= simple_form_for(@employee, remote: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= text %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :last_name %>
    <%= f.input :position %>
    <%= f.input :email %>
    <%= f.input :private_number %>
  </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= f.submit "Save employee", :class => 'btn btn-primary create-button' %>
      </div>
    </div>
    <% end %>
  </div>




  

reloj_checador_team03/app/views/employees/_search.erb
<% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.position %></td>
        <td><%= employee.email %></td>
        <td><%= employee.private_number %></td>
        <td><i class="far fa-edit"></i><%= link_to 'Edit', edit_employee_path(employee), remote: true %> &nbsp <i class="fas fa-user-times"></i><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

reloj_checador_team03/app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

reloj_checador_team03/app/views/employees/edit.js.erb
$("#employee-modal").html("<%= j render 'form' %>");
$('#employee-modal').modal('show');

reloj_checador_team03/app/views/employees/index.html.erb
<%= toastr_flash %>
<h1>List Employees</h1>
<div class="container-content">
<div class="d-flex justify-content-between bd-highlight mb-3">
  <div class="d-flex justify-content-start">
     <%= form_tag(employees_search_path, method: "post", remote: true, authenticity_token: true, role: "form",class: "form") do %>
     <%= text_field_tag('search', nil, placeholder: 'Enter search term...', class: 'form-control') %>
     <% end %>
</div>
<div class="d-flex justify-content-center">
  <%= link_to 'New employee', new_employee_path(Employee.new), remote: true, :class=> "btn btn-success create-button" %>
</div>
</div>
<div class="modal fade" id="employee-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<%= render "form"  %>
</div>
<table class="table">
  <thead class="table-thead">
    <tr>
      <th class="table-thead-th">Name</th>
      <th class="table-thead-th">Last name</th>
      <th class="table-thead-th">Position</th>
      <th class="table-thead-th">Email</th>
      <th class="table-thead-th">Private number</th>
      <th class="table-thead-th">Actions</th>
    </tr>
  </thead>

  <tbody id="employee-table-body">
    <%= render 'search', remote: true %>
  </tbody>
</table>
<%= paginate @employees %>

</div>

reloj_checador_team03/app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

reloj_checador_team03/app/views/employees/new.js.erb
$("#employee-modal").html("<%= j render 'form' %>");
$('#employee-modal').modal('show');

reloj_checador_team03/app/views/employees/search.js.erb
$('#employee-table-body').html("<%= j (render 'search', employees: @employees) %>")

reloj_checador_team03/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @employee.position %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Private number:</strong>
  <%= @employee.private_number %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>